### ISSUE TITLE
Constant writing to console

### ISSUE THREAD

**Issue by gordonthree** [damoclark/node-red-contrib-gpsd#1]
GPSd node is constantly generating node-red console messages like this, at a frequency roughly 1 per second:

6 Apr 10:42:00 - [info] [gpsd:GPSd] data={"class":"SKY","tag":"MID4","device":"/dev/ttyUSB0","time":"2017-04-06T14:41:59.000Z","xdop":0.78,"ydop":1,"vdop":2.12,"tdop":1.51,"hdop":0.8,"gdop":2.89,"pdop":2.47,"satellites":[{"PRN":26,"el":20,"az":174,"ss":33,"used":true},{"PRN":1,"el":22,"az":273,"ss":26,"used":true},{"PRN":3,"el":24,"az":313,"ss":37,"used":true},{"PRN":25,"el":38,"az":66,"ss":37,"used":true},{"PRN":32,"el":52,"az":85,"ss":49,"used":true},{"PRN":22,"el":45,"az":297,"ss":50,"used":true},{"PRN":10,"el":20,"az":154,"ss":39,"used":true},{"PRN":31,"el":82,"az":240,"ss":49,"used":true},{"PRN":14,"el":73,"az":45,"ss":45,"used":true},{"PRN":12,"el":10,"az":31,"ss":44,"used":true},{"PRN":138,"el":34,"az":208,"ss":43,"used":false}]}

which is generating huge logs and lots of disk IO. Is there a way to inhibit this logging, I can't find a switch anywhere to turn it off.

**Comment by damoclark** [comment]
Hi @gordonthree,

Been meaning to get to this issue as it's been a nuisance for me too.

Try updating to v1.0.1

D.

**Comment by gordonthree** [comment]
@damoclark That did the trick, debug output is greatly reduced

1|node-red | 6 Apr 22:13:03 - [info] Server now running at http://127.0.0.1:1880/
1|node-red | 6 Apr 22:13:03 - [info] Starting flows
1|node-red | 6 Apr 22:13:04 - [info] [gpsd:GPSd] Registering "tpv" event
1|node-red | 6 Apr 22:13:04 - [info] [gpsd:GPSd] Registering "sky" event
1|node-red | 6 Apr 22:13:04 - [info] [gpsd:GPSd] Registering "device" event
1|node-red | 6 Apr 22:13:04 - [info] Started flows
1|node-red | 6 Apr 22:13:04 - [info] Socket connected.
1|node-red | 6 Apr 22:13:04 - [info] [gpsd:GPSd] Connected to gpsd

Thank you for the super fast response!
