### ISSUE TITLE
The version published to the NodeRED palette is still 1.0.4

### ISSUE THREAD

**Issue by j9brown** [damoclark/node-red-contrib-gpsd#11]
As seen in the [NodeRED listing for gpsd](https://flows.nodered.org/node/node-red-contrib-gpsd), the currently published version of this node is 1.0.4 which lacks certain fixes made in more recent versions.  Moreover, the Palette Manager in NodeRED only offers 1.0.4 for installation.

I'm reporting this because I'm having issues with gpsd not reconnecting after the service restarts and it seems that my instance is not even running the latest code.  Is it time to publish a new release?

According to the docsite, [updated nodes are no longer automatically added to the index](https://nodered.org/docs/creating-nodes/packaging#adding-to-flowsnoderedorg).

**Comment by j9brown** [comment]
I was able to work around the issue locally by performing the following actions:

* Check out the repository
* Run `npm install`
* Run `npm pack`
* In the NodeRED editor, click 'Manage palette', switch to 'Install', click 'Upload module tgz file' button
* Select the tgz file that was created earlier by `npm pack`

**Comment by damoclark** [comment]
Thanks for the guidance on resolving this @j9brown 

I've updated accordingly and gpsd now appears as v1.0.7 in flows.nodered.org
