### ISSUE TITLE
If node-gpsd throws an error, Node-RED crashes; it should continue

### ISSUE THREAD

**Issue by Ozzard** [damoclark/node-red-contrib-gpsd#8]
node-gpsd can emit a Node.JS 'error' event under rare circumstances.  These are treated specially by the Node runtime: if there are no listeners for an error, Node exits.  This was a little... unexpected... the first time I encountered it!

The fix is to include a handler for 'error' on node-gpsd.

**Comment by Ozzard** [comment]
I have working code to fix this and will submit a PR.

**Comment by damoclark** [comment]
Thanks Peter for the PR.

**Comment by Ozzard** [comment]
No problem.  When are you likely to put out a new release, so that I know when I can ditch my npm registry's local copy and go back to yours?

**Comment by damoclark** [comment]
Don't have much time these days for community coding.  Thanks for the reminder.  

I can knock out a release tomorrow.  

D.

**Comment by damoclark** [comment]
Published as 1.0.7
